import { useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import {
  Bot,
  CheckCircle,
  Download,
  FileUp,
  MessageSquare,
  Shield,
  Sparkles,
} from "lucide-react";
import { useDashboardData } from "../../../hooks/useDashboardData";
import type { RecentActivityItem } from "../../../lib/api";
import { DashboardCard } from "./shared/DashboardCard";
import SectionHeader from "./shared/SectionHeader";
import LazySection from "./shared/LazySection";
import { Skeleton } from "../../../design/components/Loading";
import { cn } from "../../../lib/utils";

const TYPE_CONFIG: Record<
  string,
  { icon: typeof Bot; color: string; label: string }
> = {
  summary: { icon: Sparkles, color: "text-purple-400", label: "Meeting summarized" },
  task: { icon: CheckCircle, color: "text-emerald-400", label: "Task generated" },
  document: { icon: FileUp, color: "text-blue-400", label: "Document uploaded" },
  security: { icon: Shield, color: "text-amber-400", label: "OTP verified" },
  message: { icon: MessageSquare, color: "text-cyan-400", label: "AI responded" },
  export: { icon: Download, color: "text-pink-400", label: "Export completed" },
  knowledge: { icon: Bot, color: "text-aether-400", label: "Knowledge indexed" },
};

function formatTime(iso: string): string {
  const date = new Date(iso);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  if (diffMins < 1) return "Just now";
  if (diffMins < 60) return `${diffMins}m ago`;
  const diffHours = Math.floor(diffMins / 60);
  if (diffHours < 24) return `${diffHours}h ago`;
  return date.toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

function TimelineContent() {
  const { loading, overview, summaries, documents, tasks } = useDashboardData();
  const navigate = useNavigate();

  const events = useMemo(() => {
    const items: Array<{
      id: string;
      type: string;
      title: string;
      description: string;
      created_at: string;
      href?: string;
    }> = [];

    (overview?.recent_activity ?? []).forEach((a: RecentActivityItem) => {
      items.push({ ...a, href: "/dashboard" });
    });

    summaries.slice(0, 3).forEach((s) => {
      items.push({
        id: `summary-${s.id}`,
        type: "summary",
        title: s.title,
        description: "Meeting summarized by AI",
        created_at: s.created_at,
        href: "/summaries",
      });
    });

    documents.slice(0, 2).forEach((d) => {
      items.push({
        id: `doc-${d.id}`,
        type: "document",
        title: d.title,
        description: d.ai_summary ? "Knowledge indexed" : "Document uploaded",
        created_at: d.created_at,
        href: "/knowledge",
      });
    });

    tasks
      .filter((t) => t.ai_generated)
      .slice(0, 2)
      .forEach((t) => {
        items.push({
          id: `task-${t.id}`,
          type: "task",
          title: t.title,
          description: "Task generated by AI",
          created_at: t.created_at,
          href: "/tasks",
        });
      });

    return items
      .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
      .slice(0, 10);
  }, [overview, summaries, documents, tasks]);

  if (loading) {
    return <Skeleton className="h-64 rounded-2xl" aria-busy="true" />;
  }

  return (
    <DashboardCard variant="glass" padding="lg" hover={false}>
      <div className="relative">
        <div className="absolute left-[15px] top-2 bottom-2 w-px bg-gradient-to-b from-ds-primary/50 via-ds-primary/20 to-transparent" aria-hidden="true" />

        <div className="space-y-4">
          {events.length === 0 ? (
            <p className="text-sm text-ds-text-muted pl-8">No recent AI activity yet.</p>
          ) : (
            events.map((event, i) => {
              const config = TYPE_CONFIG[event.type] ?? TYPE_CONFIG.message;
              const Icon = config.icon;

              return (
                <motion.button
                  key={event.id}
                  type="button"
                  initial={{ opacity: 0, x: -12 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.05 }}
                  onClick={() => event.href && navigate(event.href)}
                  className="w-full flex items-start gap-4 text-left group"
                >
                  <div
                    className={cn(
                      "relative z-10 w-8 h-8 rounded-full flex items-center justify-center shrink-0",
                      "bg-ds-surface border border-ds-border group-hover:border-ds-primary/40 transition-colors"
                    )}
                  >
                    <Icon className={cn("w-3.5 h-3.5", config.color)} />
                  </div>
                  <div className="flex-1 min-w-0 pt-0.5">
                    <div className="flex items-center justify-between gap-2">
                      <p className="text-sm font-medium text-ds-text-primary truncate group-hover:text-ds-primary transition-colors">
                        {event.title}
                      </p>
                      <time className="text-[10px] text-ds-text-muted shrink-0 tabular-nums">
                        {formatTime(event.created_at)}
                      </time>
                    </div>
                    <p className="text-xs text-ds-text-muted">{event.description || config.label}</p>
                  </div>
                </motion.button>
              );
            })
          )}
        </div>
      </div>
    </DashboardCard>
  );
}

export default function AIActivityTimeline() {
  return (
    <section aria-label="AI activity timeline">
      <SectionHeader title="AI Activity Timeline" subtitle="Latest intelligent actions across your workspace" />
      <LazySection>
        <TimelineContent />
      </LazySection>
    </section>
  );
}
